config/routes.rb
Rails.application.routes.draw do
  resources :posts
	root to: "posts#index"
  devise_for :admins
  get 'pages/index'
	root to: "pages#index"
	
  devise_for :users
  devise_scope :user do
	get '/users/sign_out' => 'devise/sessions#destroy'

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    def initialize(user)
	 user ||= User.new
	 if user.role == "admin"
	   can :manage, :all
	 elsif user.role == "team_member"
	   alias_action :create, :read, :update, :to => :cru
	   can :cru,  :all
	  end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new]
 
  def index
  end
 
  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alkimii Test</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
	<%= render "shared/navigation" %>
 
	<p class="alert"><%= alert %></p>
  </div>
 
  <div class="container-fluid">
    <%= yield %>
  </div>
 
</body>
</html>

app/views/pages/home_index.html.erb
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1>Welcome</h1>
    <p class="lead">
      You have logged successfully!  If this were a real app some sweet content
      would go here.  But it's just a test.  You might want to sign out now.
    </p>
    <%= link_to "Log Out", destroy_user_session_path, :method => :delete, :class => 'btn btn-large btn-danger' %>
  <% else %>
    <h2>Welcome, new user!</h2>
    <p class="lead">
      You must sign in or sign up before you can access our super sweet,
      top secret content.
    </p>
    <div class="row-fluid">
      <div class="span6">
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
      </div>
      <div class="span6">
        <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field_title">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field field_body">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="jumbotron">
	<h2>Editing Post</h2>

	<%= render 'form', post: @post %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path, { :class=>"btn btn-success" }%>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <div class="jumbotron welcome">
    <%= image_tag("welcome.png", :alt => "rss feed") %>
    <p class="lead">
      You have logged like a Team member successfully!  If this were a real app some sweet content
      would go here.  But it's just a test.  You might want to sign out now.
    </p>
  </div>
  <div class="jumbotron">
	<h3>Latest Post</h3>

	<table>
	  <thead>
		<tr>
		  <th></th>
		  <th></th>
		  <th colspan="1"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @posts.each do |post| %>
		  <tr>
			<td><%= image_tag("note_icon.png", :alt => "rss feed") %></td>
			<td><%= post.title %></td>
			<td><%= link_to 'Show', post ,{ :class=>"link-success" }%></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
	<br/>
	<%= link_to 'New Post', new_post_path, { :class=>"btn btn-success" }%>
	
  </div>
	<br>
  <div class="jumbotron">
	<p class="lead">
      If you want to log out
    </p><%= link_to "Log Out", destroy_user_session_path, :method => :delete, :class => 'btn btn-cancel' %>
  </div>
  <% elsif admin_signed_in? %>
	 <div class="jumbotron welcome">
    <%= image_tag("welcome.png", :alt => "rss feed") %>
    <p class="lead">
      You have logged like an Admin successfully!  If this were a real app some sweet content
      would go here.  But it's just a test.  You might want to sign out now.
    </p>
  </div>
  <div class="jumbotron">
	<h3>Latest Post</h3>

	<table>
	  <thead>
		<tr>
		  <th></th>
		  <th></th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @posts.each do |post| %>
		  <tr>
			<td><%= image_tag("note_icon.png", :alt => "rss feed") %></td>
			<td><%= post.title %></td>
			<td><%= link_to 'Show', post ,{ :class=>"link-success" }%></td>
			<td><%= link_to 'Edit', edit_post_path(post),{ :class=>"link-success" } %></td>
			<td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?',:class=>"link-success" } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
	<br/>
	<%= link_to 'New Post', new_post_path, { :class=>"btn btn-success" }%>
	
  </div>
	<br>
  <div class="jumbotron">
	<p class="lead">
      If you want to log out
    </p><%= link_to "Log Out", destroy_user_session_path, :method => :delete, :class => 'btn btn-cancel' %>
  </div>
  <% else %>
	<div class="jumbotron">
		<h2><%= image_tag("welcome.png", :alt => "rss feed") %></h2>
		<br/><br/><br/><br/>
		<p class="lead">
		  You must log in or sign up before you can access our super sweet test code.
		</p>
		<br><br>
		<div class="row-fluid">
		  <div class="span6">
			<%= link_to "Log In", new_user_session_path, :class => "btn btn-success" %>
			<%= link_to "User Sign Up", new_user_registration_path, :class => "btn btn-login" %>
			<%= link_to "Admin Sign Up", new_admin_registration_path, :class => "btn btn-login" %>
		  </div>
		  <div class="span6">
			
		  </div>
		</div>
	</div>
  <% end %>

app/views/posts/new.html.erb
<div class="jumbotron">
	<h2>New Post</h2>

	<%= render 'form', post: @post %>
	<br/>
	<%= link_to 'Back', posts_path,{ :class=>"btn btn-success" } %>
</div>

app/views/posts/show.html.erb
<div class="jumbotron">
	<p id="notice"><%= notice %></p>
	<p>
	  <strong><%= @post.title %></strong>
	</p>

	<p>
	  <%= @post.body %>
	</p>

	<%= link_to 'Edit', edit_post_path(@post), { :class=>"btn btn-update" } %> 
	<%= link_to 'Back', posts_path, { :class=>"btn btn-success" }%>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
	  <%= link_to "Alkimii", "https://apps.alkimii.com/users/sign_in", :target => "_blank", class: 'navbar-brand'%>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
		  <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Team member profile<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
			</ul>
          </li>
		<% elsif admin_signed_in? %>
		  <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin profile<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
			</ul>
          </li>
        <% else %>
		  <li><%= link_to "Home", pages_index_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>